  # Encoder:
input_size : 2
pre_processing_layers : [4]
#LSTM
num_layers : 1
post_processing_layers : [256]
output_size : 256

  # Decoder:
decoder_hidden_layers : [64,32]

  # Env params:
size : [10,10]
N_obstacles : 10
borders_in_obstacles : True
visibility : 8

  # Training params:
batch_size : 1000
elements_per_sample : 4
epochs : 500
use_gpu : True
load_model : False
save_model : True